[system]
description = "Example of all of the options"
interface = "blah" # export an interface for this "aggregate component"

[[components]]
name = "ping"
img = "no_interface.ping"
# explicitly specified interface component dependencies
deps = [
    {srv = "pong", interface = "pong"},
    {srv = "capmgr", interface = "thdalloc"}
]

[[components]]
name = "pong"
img = "pong.pingpong"
deps = [{srv = "capmgr", interface = "thdalloc"}]
initargs = [
    {key = "hello", value = "world"},
    {at  = "capmgr", key = "core", value = "2"} # send an init message to another component
]

[[components]]
name = "sched"
img = "sched.fprr"
baseaddr = "0x40000000" # yeah...hex isn't represented in toml
# the "comp" variant is the default one: use a component with minimal broiler-plate
variants = [{interface = "sched", variant = "comp"}]

[[components]]
name = "capmgr"
img = "thdalloc.capmgr"
variants = [{interface = "resmgr", variant = "comp"}]
